<a href="https://colab.research.google.com/github/AnnaPoliukhovych/MachineLearning/blob/main/%D0%9F%D0%BE%D0%BB%D1%8E%D1%85%D0%BE%D0%B2%D0%B8%D1%87_%D0%9F%D0%A0_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Полюхович 4-8, 21 варіант

1. Створіть одновимірний масив (вектор) зі значеннями натуральних чисел, починаючи з 1, та виведіть його значення.

In [1]:
import numpy as np

vector = np.arange(1, 11)

vector


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

2. Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його косинусами
кожного натурального числа, починаючи з 1, та виведіть його значення.

In [2]:
import numpy as np

matrix = np.cos(np.arange(1, 10).reshape(3, 3))

matrix

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

3. Створіть масив розміром 3x3, заповніть його випадковими цілими числами від -5 до 5 та виведіть непарні числа.

In [3]:
import numpy as np

matrix = np.random.randint(-5, 6, size=(3, 3))

odd_numbers = matrix[matrix % 2 != 0]

matrix, odd_numbers

(array([[ 5, -3,  0],
        [ 0,  0,  5],
        [ 5, -2,  3]]),
 array([ 5, -3,  5,  5,  3]))

4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від -0.7 до 0.7 та виведіть його значення.

In [4]:
import numpy as np

matrix = np.random.uniform(-0.7, 0.7, size=(4, 4))

matrix

array([[-0.17557141,  0.55576893,  0.64917722,  0.43760016],
       [-0.00300847,  0.25031449, -0.2857766 ,  0.68874416],
       [-0.37903599,  0.20265519,  0.32857886, -0.66452017],
       [-0.31580036, -0.29401286,  0.30982856,  0.59856774]])

5. Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими
числами в діапазоні від 10 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [5]:
import numpy as np

# Створюємо перший масив
a = np.random.randint(10, 21, size=5)

# Створюємо другий масив
b = np.random.randint(10, 21, size=5)

# Поелементне додавання
add = a + b

# Поелементне віднімання
sub = a - b

# Поелементне множення
mul = a * b

# Виводимо обидва масиви та результати операцій
a, b, add, sub, mul

(array([14, 13, 11, 20, 16]),
 array([10, 16, 19, 16, 17]),
 array([24, 29, 30, 36, 33]),
 array([ 4, -3, -8,  4, -1]),
 array([140, 208, 209, 320, 272]))

6. Створіть дві матриці 4x4, заповніть їх довільними цілими числами від 1 до 10 та знайдіть їх добуток.

In [6]:
import numpy as np

# Створюємо дві матриці 4x4 з випадковими числами від 1 до 10
matrix1 = np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

# Знаходимо добуток матриць
product = np.dot(matrix1, matrix2)

print("\nДобуток матриць:")
print(product)

Матриця 1:
[[5 1 8 2]
 [8 6 1 3]
 [6 9 1 9]
 [5 4 6 3]]

Матриця 2:
[[ 7  1  1  5]
 [ 7  7  4 10]
 [ 7  5  9  1]
 [ 7  4 10  9]]

Добуток матриць:
[[112  60 101  61]
 [126  67  71 128]
 [175 110 141 202]
 [126  75 105  98]]


7. Створіть дві матриці розміром 2x3 та 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [7]:
import numpy as np

# Створюємо дві матриці
matrix1 = np.random.randint(1, 6, size=(2, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))

print("Матриця 1 (2x3):")
print(matrix1)

print("\nМатриця 2 (3x3):")
print(matrix2)

# Множимо матриці
product = np.dot(matrix1, matrix2)

print("\nДобуток матриць (2x3 * 3x3 = 2x3):")
print(product)

Матриця 1 (2x3):
[[5 5 5]
 [3 4 5]]

Матриця 2 (3x3):
[[5 2 2]
 [2 4 2]
 [1 3 2]]

Добуток матриць (2x3 * 3x3 = 2x3):
[[40 45 30]
 [28 37 24]]


8. Створіть матрицю розміром 2x2, заповніть її випадковими цілими числами в діапазоні від 1 до 12 та знайдіть її обернену матрицю.

In [8]:
import numpy as np

# Створюємо матрицю 2x2 з випадковими числами від 1 до 12
matrix = np.random.randint(1, 13, size=(2, 2))

print("Матриця 2x2:")
print(matrix)

# Перевіряємо, чи матриця обернена (детермінант не нуль)
det = np.linalg.det(matrix) # обчислює детермінант
if det != 0:
    inverse_matrix = np.linalg.inv(matrix) # знаходить обернену матрицю
    print("\nОбернена матриця:")
    print(inverse_matrix)
else:
    print("\nМатриця не обернена (детермінант = 0).")

Матриця 2x2:
[[10  5]
 [ 9 10]]

Обернена матриця:
[[ 0.18181818 -0.09090909]
 [-0.16363636  0.18181818]]


9. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та транспонуйте її.

In [9]:
import numpy as np

# Створюємо матрицю 3x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 3)

print("Матриця 3x3:")
print(matrix)

# Транспонуємо матрицю
transposed_matrix = matrix.T

print("\nТранспонована матриця:")
print(transposed_matrix)

Матриця 3x3:
[[0.60103208 0.49801304 0.22760682]
 [0.26762007 0.84468824 0.9620376 ]
 [0.14529563 0.36407613 0.06953336]]

Транспонована матриця:
[[0.60103208 0.26762007 0.14529563]
 [0.49801304 0.84468824 0.36407613]
 [0.22760682 0.9620376  0.06953336]]


10. Створіть матрицю розміром 3x4 та вектор розміром 4x1, заповніть матрицю
випадковими цілими числами в діапазоні від 1 до 10, а вектор - випадковими дійсними числами від 0 до 1, і знайдіть добуток матриці на вектор.

In [10]:
import numpy as np

# Створюємо матрицю 3x4 з випадковими цілими числами від 1 до 10
matrix = np.random.randint(1, 11, size=(3, 4))

# Створюємо вектор 4x1 з випадковими дійсними числами від 0 до 1
vector = np.random.rand(4, 1)

print("Матриця 3x4:")
print(matrix)

print("\nВектор 4x1:")
print(vector)

# Множимо матрицю на вектор
product = np.dot(matrix, vector)

print("\nДобуток матриці на вектор (3x1):")
print(product)

Матриця 3x4:
[[ 4  4  9  9]
 [ 3  3  7 10]
 [ 9  9  2 10]]

Вектор 4x1:
[[0.25146965]
 [0.63521324]
 [0.07118745]
 [0.21159409]]

Добуток матриці на вектор (3x1):
[[ 6.0917654 ]
 [ 5.27430169]
 [10.23846171]]


11. Створіть матрицю розміром 2x3 та вектор розміром 3x1, заповніть матрицю
випадковими дійсними числами від 0 до 1, а вектор - випадковими цілими числами в
діапазоні від 1 до 10, і знайдіть добуток матриці на вектор.

In [11]:
import numpy as np

# Створюємо матрицю 2x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(2, 3)

# Створюємо вектор 3x1 з випадковими цілими числами від 1 до 10
vector = np.random.randint(1, 11, size=(3, 1))

print("Матриця 2x3:")
print(matrix)

print("\nВектор 3x1:")
print(vector)

# Множимо матрицю на вектор
product = np.dot(matrix, vector)

print("\nДобуток матриці на вектор (2x1):")
print(product)

Матриця 2x3:
[[0.59684539 0.55385252 0.90617971]
 [0.07062769 0.89141837 0.8660203 ]]

Вектор 3x1:
[[5]
 [8]
 [5]]

Добуток матриці на вектор (2x1):
[[11.94594568]
 [11.81458694]]


12. Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в
діапазоні від 1 до 5 та знайдіть суму всіх елементів першої матриці.

In [12]:
import numpy as np

# Створюємо дві матриці 3x3 з випадковими цілими числами від 1 до 5
matrix1 = np.random.randint(1, 6, size=(3, 3))
matrix2 = np.random.randint(1, 6, size=(3, 3))

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

# Знаходимо суму всіх елементів першої матриці
sum_matrix1 = np.sum(matrix1)

print("\nСума всіх елементів першої матриці:")
print(sum_matrix1)

Матриця 1:
[[1 2 2]
 [2 1 1]
 [2 3 4]]

Матриця 2:
[[4 5 3]
 [1 5 2]
 [3 2 3]]

Сума всіх елементів першої матриці:
18


13. Створіть дві матриці розміром 4x4, заповніть їх випадковими дійсними числами в
діапазоні від -2 до 2 та знайдіть добуток їх елементів.

In [13]:
import numpy as np

# Створюємо дві матриці 4x4 з випадковими дійсними числами від -2 до 2
matrix1 = np.random.uniform(-2, 2, size=(4, 4))
matrix2 = np.random.uniform(-2, 2, size=(4, 4))

print("Матриця 1:")
print(matrix1)

print("\nМатриця 2:")
print(matrix2)

# Поелементно множимо матриці
elementwise_product = matrix1 * matrix2
print("\nПоелементний добуток матриць:")
print(elementwise_product)

# Добуток усіх елементів результату
total_product = np.prod(elementwise_product)
print("\nДобуток всіх елементів:")
print(total_product)

Матриця 1:
[[ 0.183769    1.78713222 -0.13886429  1.15130809]
 [-0.40830924 -0.60760228 -1.51225835  1.19583882]
 [-1.1424413   0.83812028 -0.18215089 -0.7320662 ]
 [ 0.86862346 -1.86701345 -0.84658438  0.87071149]]

Матриця 2:
[[ 1.98998069 -1.69032249  0.15720306 -1.23524006]
 [ 0.74654564  0.92324133 -1.71513521  1.06221676]
 [-1.6010507   1.30947875  0.39629557 -1.20168111]
 [-0.27584415  1.44380702 -1.90333166 -1.18547689]]

Поелементний добуток матриць:
[[ 0.36569677 -3.02082979 -0.02182989 -1.42214188]
 [-0.30482149 -0.56096354  2.59372755  1.27024005]
 [ 1.82910644  1.09750069 -0.07218559  0.87971012]
 [-0.2396047  -2.69560712  1.61133085 -1.03220834]]

Добуток всіх елементів:
-0.002645879987341674


14. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від -10 до 10 та знайдіть найменший елемент матриці.

In [14]:
import numpy as np

# Створюємо матрицю 3x3 з випадковими дійсними числами від -10 до 10
matrix = np.random.uniform(-10, 10, size=(3, 3))

print("Матриця 3x3:")
print(matrix)

# Знаходимо найменший елемент матриці
min_element = np.min(matrix)

print("\nНайменший елемент матриці:")
print(min_element)

Матриця 3x3:
[[-5.69959901  6.49144897 -3.52083248]
 [-6.52721107  3.56109807  6.92575344]
 [-0.60300813 -4.06216665 -9.95772553]]

Найменший елемент матриці:
-9.957725534004027


15. Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в
діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного
стовпця матриці.

In [15]:
import numpy as np

# Створюємо матрицю 3x3 з випадковими дійсними числами від 0 до 1
matrix = np.random.rand(3, 3)

print("Матриця 3x3:")
print(matrix)

# Знаходимо суму елементів по стовпцях
column_sums = np.sum(matrix, axis=0)

# Перетворюємо вектор рядок у вектор-стовпчик
column_sums_column_vector = column_sums.reshape(-1, 1)

print("\nВектор-стовпчик сум елементів кожного стовпця:")
print(column_sums_column_vector)

Матриця 3x3:
[[0.84209728 0.55010381 0.15717833]
 [0.1542725  0.08033064 0.27242276]
 [0.14045158 0.35750211 0.79458533]]

Вектор-стовпчик сум елементів кожного стовпця:
[[1.13682136]
 [0.98793656]
 [1.22418642]]


Висновок: В ході виконання лабораторної роботи ми навчилися створювати та обробляти одновимірні та двовимірні масиви у Python за допомогою numpy. Було виконано генерацію масивів з різними типами чисел, поелементні операції, сумування елементів, транспонування, множення матриць і векторів, а також знаходження обернених та мінімальних значень.